version: '3.8'  # version un peu plus récente

services:
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    image: php:8.1-apache
    container_name: Gestion1_php
    volumes:
      - ./src:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - app_network

  mysql:
    image: mysql:8.0
    container_name: Gestion1_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Gestion1_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./projet-web-docker/docker/mysql/initdb:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: Gestion1_phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: user
      PMA_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"   # Accessible sur localhost:8081
    depends_on:
      - mysql
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mysql_data:
